name: Dotnet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - uses: actions/checkout@v3
    
#     download artifact
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: Display structure of downloaded files
      run: ls -R
      
#     upload artifact
    - uses: actions/upload-artifact@v3
      with:
        name: harness-build-log
        path: bin/output/logs/harness.log
        retention-days: 12

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: ${{secrets.BUILD}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
